config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  resources :takoyakis
root 'pages#landing'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/takoyaki.rb
class Takoyaki < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/controllers/takoyakis_controller.rb
class TakoyakisController < ApplicationController
  before_action :set_takoyaki, only: [:show, :edit, :update, :destroy]

  # GET /takoyakis
  # GET /takoyakis.json
  def index
    @takoyakis = Takoyaki.all
  end

  # GET /takoyakis/1
  # GET /takoyakis/1.json
  def show
  end

  # GET /takoyakis/new
  def new
    @takoyaki = Takoyaki.new
  end

  # GET /takoyakis/1/edit
  def edit
  end

  # POST /takoyakis
  # POST /takoyakis.json
  def create
    @takoyaki = Takoyaki.new(takoyaki_params)

    respond_to do |format|
      if @takoyaki.save
        format.html { redirect_to @takoyaki, notice: 'Takoyaki was successfully created.' }
        format.json { render :show, status: :created, location: @takoyaki }
      else
        format.html { render :new }
        format.json { render json: @takoyaki.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /takoyakis/1
  # PATCH/PUT /takoyakis/1.json
  def update
    respond_to do |format|
      if @takoyaki.update(takoyaki_params)
        format.html { redirect_to @takoyaki, notice: 'Takoyaki was successfully updated.' }
        format.json { render :show, status: :ok, location: @takoyaki }
      else
        format.html { render :edit }
        format.json { render json: @takoyaki.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /takoyakis/1
  # DELETE /takoyakis/1.json
  def destroy
    @takoyaki.destroy
    respond_to do |format|
      format.html { redirect_to takoyakis_url, notice: 'Takoyaki was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_takoyaki
      @takoyaki = Takoyaki.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def takoyaki_params
      params.require(:takoyaki).permit(:price, :quantity_oct)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/takoyakis_helper.rb
module TakoyakisHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Egg</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/pages/landing.html.erb
HELLO WORLD

app/views/takoyakis/_form.html.erb
<%= form_with(model: takoyaki, local: true) do |form| %>
  <% if takoyaki.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(takoyaki.errors.count, "error") %> prohibited this takoyaki from being saved:</h2>

      <ul>
      <% takoyaki.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :takoyaki_price %>
  </div>

  <div class="field">
    <%= form.label :quantity_oct %>
    <%= form.number_field :quantity_oct, id: :takoyaki_quantity_oct %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/takoyakis/edit.html.erb
<h1>Editing Takoyaki</h1>

<%= render 'form', takoyaki: @takoyaki %>

<%= link_to 'Show', @takoyaki %> |
<%= link_to 'Back', takoyakis_path %>

app/views/takoyakis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Takoyakis</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Quantity oct</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @takoyakis.each do |takoyaki| %>
      <tr>
        <td><%= takoyaki.price %></td>
        <td><%= takoyaki.quantity_oct %></td>
        <td><%= link_to 'Show', takoyaki %></td>
        <td><%= link_to 'Edit', edit_takoyaki_path(takoyaki) %></td>
        <td><%= link_to 'Destroy', takoyaki, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Takoyaki', new_takoyaki_path %>

app/views/takoyakis/new.html.erb
<h1>New Takoyaki</h1>

<%= render 'form', takoyaki: @takoyaki %>

<%= link_to 'Back', takoyakis_path %>

app/views/takoyakis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @takoyaki.price %>
</p>

<p>
  <strong>Quantity oct:</strong>
  <%= @takoyaki.quantity_oct %>
</p>

<%= link_to 'Edit', edit_takoyaki_path(@takoyaki) %> |
<%= link_to 'Back', takoyakis_path %>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :tweet_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :tweet_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.title %></td>
        <td><%= tweet.body %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tweet.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @tweet.body %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>